admin/models/Book.php
<?php

namespace admin\models;

use Isbn\Isbn;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * This is the model class for table "book".
 *
 * @property string $id
 * @property string $internal_id
 * @property string $name
 * @property integer $page_count
 * @property string $isbn
 * @property string $issn
 * @property integer $language_id
 * @property string $library_id
 * @property string $publisher_id
 * @property integer $type_id
 * @property integer $status_id
 * @property integer $category_id
 * @property integer $edition
 * @property integer $year
 * @property string $description
 * @property string $created_at
 * @property string $updated_at
 *
 * @property Category $category
 * @property Language $language
 * @property Library $library
 * @property Publisher $publisher
 * @property Status $status
 * @property Type $type
 * @property BookAuthor[] $bookAuthors
 * @property Author[] $authors
 * @property BookKeyWord[] $bookKeyWords
 * @property KeyWord[] $keyWords
 * @property LogCrud[] $logCruds
 * @property RentalBook[] $rentalBooks
 * @property Rental[] $rentals
 */
class Book extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'book';
    }

    /**
     * Validation rules
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [
                [
                    'internal_id',
                    'name',
                    'language_id',
                    'library_id',
                    'publisher_id',
                    'type_id',
                    'status_id',
                    'category_id'
                ],
                'required'
            ],
            [
                [
                    'page_count',
                    'language_id',
                    'library_id',
                    'publisher_id',
                    'type_id',
                    'status_id',
                    'category_id',
                    'edition',
                    'year'
                ],
                'integer'
            ],
            [['description'], 'string'],
            [['description'], 'stripTags'],
            [['updated_at', 'created_at'], 'safe'],
            [['internal_id'], 'string', 'max' => 11],
            [['name'], 'string', 'max' => 255],
            [['isbn', 'issn'], 'string', 'max' => 20],
            [['isbn', 'issn'], 'validateISBN'],
            [['internal_id'], 'unique'],
            [['year'], 'integer', 'max' => 2999, 'min' => 1900],
        ];
    }


    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * strip HTML and php tags
     * @return string
     */
    public function stripTags()
    {
        return strip_tags($this->description);
    }

    /**
     * Validate correct ISBN/ISSN format
     */
    public function validateISBN()
    {
        $isbn = new Isbn();
        if (!empty($this->isbn)) {
            if ($isbn->validation->isbn($this->isbn) === false) {
                $this->addError('isbn', Yii::t('app', 'Not valid {isbn}', ['isbn' => 'isbn']));
            } else {
                $this->isbn = $isbn->hyphens->fixHyphens($this->isbn);
            }
        }
        if (!empty($this->issn)) {
            if ($isbn->validation->isbn($this->issn) === false) {
                $this->addError('issn', Yii::t('app', 'Not valid {isbn}', ['isbn' => 'issn']));
            } else {
                $this->issn = $isbn->hyphens->fixHyphens($this->issn);
            }
        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'internal_id' => Yii::t('app', 'Internal ID'),
            'name' => Yii::t('app', 'Book name'),
            'page_count' => Yii::t('app', 'Page Count'),
            'isbn' => Yii::t('app', 'Isbn'),
            'issn' => Yii::t('app', 'Issn'),
            'language_id' => Yii::t('app', 'Language'),
            'library_id' => Yii::t('app', 'Library'),
            'publisher_id' => Yii::t('app', 'Publisher'),
            'type_id' => Yii::t('app', 'Type'),
            'status_id' => Yii::t('app', 'Status'),
            'category_id' => Yii::t('app', 'Category'),
            'edition' => Yii::t('app', 'Edition'),
            'year' => Yii::t('app', 'Year'),
            'description' => Yii::t('app', 'Description'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'created_at' => Yii::t('app', 'Created At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

    /*public function getCategoryName()
    {
        return $this->getCategory()->asArray()->one()['category_name'];
    }*/

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLanguage()
    {
        return $this->hasOne(Language::className(), ['id' => 'language_id']);
    }

    public function getLanguageName()
    {
        return $this->getLanguage()->asArray()->one()['name'];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLibrary()
    {
        return $this->hasOne(Library::className(), ['id' => 'library_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPublisher()
    {
        return $this->hasOne(Publisher::className(), ['id' => 'publisher_id']);
    }

    public function getPublisherName()
    {
        return $this->getPublisher()->asArray()->one()['name'];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(Status::className(), ['id' => 'status_id']);
    }

    public function getStatusName()
    {
        return Yii::t('app', $this->getStatus()->asArray()->one()['status']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getType()
    {
        return $this->hasOne(Type::className(), ['id' => 'type_id']);
    }

    /*public function getTypeName()
    {
        return Yii::t('app', $this->getType()->asArray()->one()['type']);
    }*/

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBookAuthors()
    {
        return $this->hasMany(BookAutho::className(), ['book_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthors()
    {
        return $this->hasMany(Author::className(), ['id' => 'author_id'])->viaTable('book_author', ['book_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBookKeyWords()
    {
        return $this->hasMany(BookKeyWord::className(), ['book_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKeyWords()
    {
        return $this->hasMany(KeyWord::className(), ['id' => 'key_word_id'])->viaTable('book_key_word',
            ['book_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRentalBooks()
    {
        return $this->hasMany(RentalBook::className(), ['book_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRentals()
    {
        return $this->hasMany(Rental::className(), ['id' => 'rental_id'])->viaTable('rental_book', ['book_id' => 'id']);
    }
}

admin/controllers/BookController.php
<?php

namespace admin\controllers;

use admin\models\Author;
use admin\models\Book;
use admin\models\BookForm;
use admin\models\BookSearch;
use admin\models\KeyWord;
use admin\models\Model;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * BookController implements the CRUD actions for Book model.
 */
class BookController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['logout', 'index', 'view', 'create', 'update', 'delete', 'harddelete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'harddelete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Book models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BookSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Book model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        $modelBook = $this->findModel($id);
        $modelBookForm = new BookForm($modelBook);

        return $this->render('view', [
            'modelBook' => $modelBook,
            'authors' => $modelBookForm->getAuthors(),
            'keyWords' => $modelBookForm->getKeyWords(),
        ]);
    }

    /**
     * Creates a new Book model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $modelBook = new Book;
        $modelBookForm = new BookForm($modelBook);
        $modelsAuthor = [new Author];
        $modelsKeyWords = [new KeyWord];

        if ($modelBook->load(Yii::$app->request->post())) {
            $modelsAuthor = Model::createMultiple(Author::className());
            Model::loadMultiple($modelsAuthor, Yii::$app->request->post());
            //process, separate book keyWords
            if ($wordsArray = $modelBookForm->prepareKeyWords(Yii::$app->request->post('KeyWord')['words'])) {
                $modelsKeyWords = Model::createMultiple(KeyWord::className(), [], $wordsArray);
                // KeyWord[0]['word' =>'php']
                Model::loadMultiple($modelsKeyWords, $wordsArray, '');
            }

            //before validation we need insert fake internal_id
            $modelBook->internal_id = '00000000000';
            // validate all models
            $valid = $modelBook->validate();
            $valid = Model::validateMultiple($modelsAuthor) && $valid;
            $valid = $wordsArray === false ? $valid : Model::validateMultiple($modelsKeyWords) && $valid;

            if ($valid && $modelBookForm->createBook($modelsAuthor, $modelsKeyWords)) {
                Yii::info($modelBook->id . '_create', 'book');
                $this->redirect(['view', 'id' => $modelBook->id]);
            }
        }

        return $this->render('create', [
            'modelBook' => $modelBook,
            'modelsAuthor' => (empty($modelsAuthor)) ? [new Author] : $modelsAuthor,
        ]);
    }

    /**
     * Updates an existing Book model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @var Author[] $modelsAuthorNew
     * @param string $id Book id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $modelBook = $this->findModel($id);
        $modelBookForm = new BookForm($modelBook);
        $authorsId = $modelBook->getAuthors()->select('id')->asArray()->all();
        $modelsAuthor = Author::findAll($authorsId); //$modelBook->getAuthors()->asArray()->all();

        if ($modelBook->load(Yii::$app->request->post())) {
            $modelsAuthorNew = Model::createMultiple(Author::className());
            Model::loadMultiple($modelsAuthorNew, Yii::$app->request->post());
            //process, separate book keyWords
            $modelsKeyWordsNew = [new KeyWord];
            if ($wordsArray = $modelBookForm->prepareKeyWords(Yii::$app->request->post('KeyWord')['words'])) {
                $modelsKeyWordsNew = Model::createMultiple(KeyWord::className(), [], $wordsArray);
                // KeyWord[0]['word' =>'php']
                Model::loadMultiple($modelsKeyWordsNew, $wordsArray, '');
            }
            $valid = $modelBook->validate();
            $valid = Model::validateMultiple($modelsAuthorNew) && $valid;
            $valid = $wordsArray === false ? $valid : Model::validateMultiple($modelsKeyWordsNew) && $valid;

            if ($valid && $modelBookForm->updateBook($modelsAuthor, $modelsAuthorNew, $modelsKeyWordsNew)) {
                Yii::$app->session->setFlash('success', Yii::t('app', Yii::t('app', 'Book was updated successfully.')));
                Yii::info($id . '_update', 'book');

                return $this->redirect(['view', 'id' => $modelBook->id]);
            } else {
                //get all errors from multiple models
                if (($msg = BookForm::getErrorsMessages($modelsAuthorNew)) !== false) {
                    Yii::$app->session->addFlash('danger', $msg);
                }
                if (($msg = BookForm::getErrorsMessages($modelsKeyWordsNew)) !== false) {
                    Yii::$app->session->addFlash('danger', $msg);
                }
            }
            Yii::$app->session->addFlash('danger', Yii::t('app', 'Book was not updated.'));
        }

        return $this->render('update', [
            'modelBook' => $modelBook,
            'modelsAuthor' => (empty($modelsAuthor)) ? [new Author] : $modelsAuthor,
            'keyWords' => $modelBookForm->getKeyWords(),
        ]);
    }

    /**
     * Deletes an existing Book model changing book status to deleted.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $book = $this->findModel($id);
        $book->status_id = Yii::$app->params['status']['deleted'];
        $book->update(false);
        Yii::info($id . '_delete', 'book');
        Yii::$app->session->addFlash('success', Yii::t('app', 'Book was deleted successfully.'));

        return $this->redirect(['index']);
    }

    /**
     * Deletes an existing Book model and all related data.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionHarddelete($id)
    {
        $modelBook = $this->findModel($id);
        $modelBookForm = new BookForm($modelBook);
        if ($modelBookForm->deleteBook()) {
            Yii::info($id . '_harddelete', 'book');
            Yii::$app->session->addFlash('success', Yii::t('app', 'Book was deleted successfully.'));

            return $this->redirect(['index']);
        }
        Yii::$app->session->addFlash('danger', Yii::t('app', 'Book was not deleted.'));

        return $this->redirect(['view', 'id' => $modelBook->id]);

    }

    /**
     * Finds the Book model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Book the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Book::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
        }
    }
}

admin/views/book/_form.php
<?php

use admin\models\BookForm;
use admin\models\Category;
use admin\models\Language;
use admin\models\Library;
use admin\models\Publisher;
use admin\models\Status;
use admin\models\Type;
use wbraganca\dynamicform\DynamicFormWidget;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $modelBook admin\models\Book */
/* @var $form yii\widgets\ActiveForm */
?>

    <div class="book-form">

        <?php $form = ActiveForm::begin(['id' => 'book-dynamic-form']); ?>

        <?= $form->field($modelBook, 'name')->textInput(['maxlength' => 255]) ?>

        <?php DynamicFormWidget::begin([
            'widgetContainer' => 'dynamicform_wrapper', // required: only alphanumeric characters plus "_" [A-Za-z0-9_]
            'widgetBody' => '.container-items', // required: css class selector
            'widgetItem' => '.item', // required: css class
            'limit' => 10, // the maximum times, an element can be added (default 999)
            'min' => 1, // 0 or 1 (default 1)
            'insertButton' => '.add-item', // css class
            'deleteButton' => '.remove-item', // css class
            'model' => $modelsAuthor[0],
            'formId' => 'book-dynamic-form',
            'formFields' => [
                'first_name',
                'last_name',
            ],
        ]); ?>

        <div class="panel-body">
            <div class="container-items"><!-- widgetBody -->
                <?php foreach ($modelsAuthor as $i => $modelAuthor): ?>
                    <div class="item panel panel-default"><!-- widgetItem -->
                        <div class="panel-heading">
                            <h3 class="panel-title pull-left"><?= Yii::t('app', 'Author') ?></h3>

                            <div class="pull-right">
                                <button type="button" class="add-item btn btn-success btn-xs"><i
                                        class="glyphicon glyphicon-plus"></i></button>
                                <button type="button" class="remove-item btn btn-danger btn-xs"><i
                                        class="glyphicon glyphicon-minus"></i></button>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="panel-body">
                            <?php
                            // necessary for update action.
                            if (!$modelAuthor->isNewRecord) {
                                echo Html::activeHiddenInput($modelAuthor, "[{$i}]id");
                            }
                            ?>
                            <div class="row">
                                <div class="col-sm-6">
                                    <?= $form->field($modelAuthor,
                                        "[{$i}]first_name")->textInput(['maxlength' => true]) ?>
                                </div>
                                <div class="col-sm-6">
                                    <?= $form->field($modelAuthor,
                                        "[{$i}]last_name")->textInput(['maxlength' => true]) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <?php DynamicFormWidget::end(); ?>


        <?= $form->field($modelBook, 'isbn')->textInput(['maxlength' => 20, 'placeholder' => '8881837188']) ?>

        <?= $form->field($modelBook, 'issn')->textInput(['maxlength' => 20, 'placeholder' => '8881837188']) ?>

        <?= $form->field($modelBook, 'page_count')->textInput() ?>

        <?= $form->field($modelBook, 'language_id')->dropDownList(BookForm::createArrayMap(Language::className(), 'id',
            'name')) ?>

        <?= $form->field($modelBook, 'publisher_id')->dropDownList(BookForm::createArrayMap(Publisher::className(),
            'id', 'name')) ?>

        <?= $form->field($modelBook, 'type_id')->dropDownList(BookForm::createArrayMapTranslate(Type::className(), 'id',
            'type')) ?>

        <?= $form->field($modelBook, 'status_id')->dropDownList(BookForm::createArrayMapTranslate(Status::className(),
            'id', 'status')) ?>

        <?= $form->field($modelBook,
            'category_id')->dropDownList(BookForm::createArrayMapTranslate(Category::className(), 'id',
            'category_name')) ?>

        <?= $form->field($modelBook, 'library_id')->dropDownList(BookForm::createArrayMap(Library::className(), 'id',
            'name')) ?>

        <?= $form->field($modelBook, 'edition')->textInput() ?>

        <?= $form->field($modelBook, 'year')->widget(yii\widgets\MaskedInput::classname(), ['mask' => '9999']); ?>

        <div class="form-group">
            <label class="control-label" for="book-key-words"><?= Yii::t('app', 'Key Words') . ' (' . Yii::t('app',
                    'Comma separated') . ')' ?></label>
            <?= Html::textInput('KeyWord[words]', isset($keyWords) ? $keyWords : null,
                ['id' => 'book-key-words', 'class' => 'form-control']) ?>
        </div>

        <?= $form->field($modelBook, 'description')->textarea(['rows' => 6]) ?>

        <div class="form-group">
            <?= Html::submitButton($modelBook->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'),
                ['class' => $modelBook->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            <?= Html::a(Yii::t('app', 'Cancel'),
                Yii::$app->request->referrer ? Yii::$app->request->referrer : ['index'],
                ['class' => 'btn btn-default']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>
<?php

$JS = '
/*$(".dynamicform_wrapper").on("beforeInsert", function(e, item) {
    console.log("beforeInsert");
});*/

/*$(".dynamicform_wrapper").on("afterInsert", function(e, item) {
    console.log("afterInsert");
});*/

$(".dynamicform_wrapper").on("beforeDelete", function(e, item) {
    if (! confirm("' . Yii::t('app', 'Are you sure you want to delete this item?') . '")) {
        return false;
    }
    return true;
});

/*$(".dynamicform_wrapper").on("afterDelete", function(e) {
    console.log("' . Yii::t('app', 'Deleted item!') . '");
});*/

$(".dynamicform_wrapper").on("limitReached", function(e, item) {
    alert("' . Yii::t('app', 'Limit reached') . '");
});

';

$this->registerJs($JS);

admin/views/book/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model admin\models\BookSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="book-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'internal_id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'page_count') ?>

    <?= $form->field($model, 'isbn') ?>

    <?php // echo $form->field($model, 'issn') ?>

    <?php // echo $form->field($model, 'language_id') ?>

    <?php // echo $form->field($model, 'library_id') ?>

    <?php // echo $form->field($model, 'publisher_id') ?>

    <?php // echo $form->field($model, 'type_id') ?>

    <?php // echo $form->field($model, 'status_id') ?>

    <?php // echo $form->field($model, 'edition') ?>

    <?php // echo $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'last_update') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

admin/views/book/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model admin\models\Book */

$this->title = Yii::t('app', 'Create Book');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Books'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="book-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'modelBook' => $modelBook,
        'modelsAuthor' => $modelsAuthor,
    ]) ?>

</div>

admin/views/book/index.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel admin\models\BookSearch */
/* @var $model admin\models\Book */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Books');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="book-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?php Pjax::begin(['timeout' => 2000]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Book'), ['create'], ['class' => 'btn btn-success', 'data-pjax' => '0']) ?>

        <?php
        $showDeletedBooks = Yii::$app->getRequest()->getQueryParam(('deleted')) == 'true' ? true : false;
        $params = Yii::$app->getRequest()->getQueryParams();
        if ($showDeletedBooks) {
            unset($params['deleted']);
            //Yii::$app->request->setQueryParams(Yii::$app->request->params);
        }
        echo Html::a(Yii::t('app', $showDeletedBooks ? 'Hide Deleted Books' : 'Show Deleted Books'),
            urldecode(Url::toRoute(array_merge(['index'], ($showDeletedBooks ? [] : ['deleted' => 'true']), $params))),
            ['class' => 'pull-right']) ?>
    </p>

    <?= \yii\widgets\LinkPager::widget([
        'pagination' => $dataProvider->pagination,
    ]);
    ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
//        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute' => 'name',
                'value' => function ($model, $id) {
                    return Html::a($model['name'], Url::to(['book/view', 'id' => $model['id']]));
                },
                'format' => 'html',
                //'search' => true,
            ],
            'isbn',
            'issn',
            [
                'attribute' => 'type_id',
                'label' => Yii::t('app', 'Type'),
                'value' => function ($model) {
                    return Yii::t('app', $model['type']);
                },
            ],
            [
                'attribute' => 'status_id',
                'label' => Yii::t('app', 'Status'),
                'value' => function ($model) {
                    return Yii::t('app', $model['status']);
                },
            ],

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {update} {delete} {harddelete}',
                'urlCreator' => function ($action, $model, $key, $index) {
                    return Url::toRoute(['book/' . $action, 'id' => $model['id']]);
                },
                'buttons' => [
                    'delete' => function ($url, $model, $key) {
                        //hide delete button if book is deleted
                        if ($model['status_id'] === Yii::$app->params['status']['deleted']) {
                            return '';
                        }
                        $options = [
                            'title' => Yii::t('yii', 'Delete'),
                            'aria-label' => Yii::t('yii', 'Delete'),
                            'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                            'data-method' => 'post',
                            'data-pjax' => '0',
                        ];

                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, $options);
                    },
                    'harddelete' => function ($url, $model, $key) {
                        $options = [
                            'title' => Yii::t('yii', 'Delete permanently'),
                            'aria-label' => Yii::t('yii', 'Delete permanently'),
                            'data-confirm' => Yii::t('app', 'Are you sure you want to delete this item?') . ' ' .
                                Yii::t('app', 'This action can not be undone'),
                            'data-method' => 'post',
                            'data-pjax' => '0',
                        ];

                        return Html::a('<span class="glyphicon glyphicon-remove"></span>', $url, $options);
                    },
                ],
            ],
        ],
    ]); ?>

    <?php Pjax::end(); ?>
</div>

admin/views/book/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model admin\models\Book */

$this->title = $modelBook->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Books'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $modelBook->name, 'url' => ['view', 'id' => $modelBook->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="book-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'modelBook' => $modelBook,
        'modelsAuthor' => $modelsAuthor,
        'keyWords' => $keyWords,
    ]) ?>

</div>